import { Dimensions, Platform, StyleSheet } from 'react-native';
import { theme } from '../../../theme';
import { PAGE_STACK_GAP } from './constants';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom: 14,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    flex: 1,
    minWidth: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: '700',
    flexShrink: 1,
    maxWidth: width * 0.6,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  actionBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabledBtn: {
    opacity: 0.4,
  },
  zoomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 20,
    marginBottom: 12,
  },
  zoomSliderWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  zoomBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomTrack: {
    flex: 1,
    position: 'relative',
    height: 20,
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  zoomFill: {
    position: 'absolute',
    left: 0,
    top: 6,
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.accentStrong,
  },
  zoomLabel: {
    minWidth: 52,
    textAlign: 'right',
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  contextBar: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 12,
    gap: 10,
  },
  contextBottomWrap: {
    marginHorizontal: 20,
    marginBottom: 24,
  },
  contextBarBottom: {
    padding: 12,
    gap: 10,
    backgroundColor: theme.colors.surface,
    marginHorizontal: 12,
    marginBottom: 12,
    borderRadius: 18,
    ...(Platform.OS === 'web'
      ? { boxShadow: `6px 6px 12px ${theme.neu.colors.darkShadow}, -6px -6px 12px ${theme.neu.colors.lightShadow}` } as any
      : {
          shadowColor: '#000',
          shadowOffset: { width: 5, height: 5 },
          shadowOpacity: 0.45,
          shadowRadius: 10,
          elevation: 8,
        }),
  },
  contextHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  contextTitle: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  doneBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.accentStrong,
  },
  doneBtnText: {
    color: theme.colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  contextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  swatchRow: {
    gap: 10,
    paddingRight: 20,
  },
  fillSignActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  fillSignActionBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  fillSignActionBtnActive: {
    backgroundColor: theme.colors.infoSoft,
  },
  signatureTray: {
    gap: 14,
  },
  signatureTabRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  signatureTab: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surfaceMuted,
  },
  signatureTabActive: {
    borderColor: theme.colors.info,
    backgroundColor: theme.colors.infoSoft,
  },
  signatureTabText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  signatureTabTextActive: {
    color: theme.colors.text,
  },
  signatureTabEditBtn: {
    marginLeft: 'auto',
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.accentStrong,
  },
  signatureTrayEmpty: {
    color: theme.colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  signatureTrayCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    backgroundColor: theme.colors.page,
    padding: 10,
  },
  signatureTrayPreview: {
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(17,17,17,0.08)',
    backgroundColor: theme.colors.page,
    overflow: 'hidden',
  },
  fontRow: {
    gap: 10,
    paddingRight: 20,
  },
  contextActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  colorSwatch: {
    width: 24,
    height: 24,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorSwatchActive: {
    borderColor: '#fff',
  },
  colorSwatchLarge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  fontChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: theme.colors.surfaceMuted,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  fontChipActive: {
    backgroundColor: theme.colors.accentStrong,
    borderColor: theme.colors.accentStrong,
  },
  fontChipText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  fontChipTextActive: {
    color: theme.colors.white,
  },
  sliderBlock: {
    gap: 10,
  },
  sliderHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sliderLabel: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  sliderValue: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  sliderTrack: {
    position: 'relative',
    height: 20,
    justifyContent: 'center',
  },
  sliderFill: {
    position: 'absolute',
    left: 0,
    top: 6,
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.accentStrong,
  },
  sliderThumb: {
    position: 'absolute',
    top: 0,
    marginLeft: -10,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: theme.colors.white,
    borderWidth: 2,
    borderColor: theme.colors.accentStrong,
  },
  miniBtn: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceSoft,
  },
  miniBtnText: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  deleteBtn: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(239,68,68,0.22)',
  },
  deleteBtnText: {
    color: '#fca5a5',
    fontSize: 12,
    fontWeight: '700',
  },
  editorArea: {
    flex: 1,
  },
  editorScrollContent: {
    minHeight: '100%',
    justifyContent: 'center',
    paddingBottom: 20,
  },
  pageWrapper: {
    minWidth: width,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  pageStack: {
    alignItems: 'center',
    gap: PAGE_STACK_GAP,
    paddingVertical: 8,
  },
  pdfPage: {
    backgroundColor: theme.colors.page,
    overflow: 'hidden',
  },
  zoomedPageFrame: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  pdfBaseLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
    transformOrigin: 'top left',
  },
  annotationScaleLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  pdfViewer: {
    width: '100%',
    height: '100%',
    backgroundColor: theme.colors.page,
  },
  inlineTextEditor: {
    position: 'absolute',
    minWidth: 180,
    maxWidth: '85%',
    zIndex: 15,
  },
  inlineTextInput: {
    paddingVertical: 4,
    paddingHorizontal: 0,
    minWidth: 160,
  },
  annotationTextContent: {
    position: 'absolute',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  textHitbox: {
    position: 'absolute',
    borderRadius: 6,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  selectedHitbox: {
    borderColor: '#60a5fa',
    backgroundColor: 'rgba(96,165,250,0.12)',
  },
  selectionHandle: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#60a5fa',
  },
  selectionHandleTopLeft: {
    left: -5,
    top: -5,
  },
  selectionHandleTopRight: {
    right: -5,
    top: -5,
  },
  selectionHandleBottomLeft: {
    left: -5,
    bottom: -5,
  },
  selectionHandleBottomRight: {
    right: -5,
    bottom: -5,
  },
  selectedTextOverlay: {
    position: 'absolute',
  },
  selectedTextContent: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  highlightHitbox: {
    position: 'absolute',
    backgroundColor: 'transparent',
  },
  selectedHighlightOverlay: {
    position: 'absolute',
  },
  selectedHighlightDragSurface: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  selectedTextDragSurface: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  resizeHandle: {
    position: 'absolute',
    right: -18,
    bottom: -18,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    zIndex: 3,
  },
  resizeHandleText: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '700',
  },
  rotationHandle: {
    position: 'absolute',
    backgroundColor: theme.colors.accentStrong,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: theme.colors.white,
    zIndex: 3,
  },
  rotationHandleText: {
    color: theme.colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  selectionActionPill: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    backgroundColor: theme.colors.bgAlt,
    borderRadius: 999,
    paddingHorizontal: 0,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 16,
  },
  selectionActionBtn: {
    paddingHorizontal: 6,
    paddingVertical: 8,
    borderRadius: 999,
  },
  selectionActionText: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  selectionPillSizeLabel: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    minWidth: 36,
  },
  selectionPillSizeText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  selectionDeleteBtn: {
    backgroundColor: 'rgba(220,38,38,0.9)',
    minWidth: 38,
    alignItems: 'center',
  },
  commentHitTarget: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'transparent',
  },
  pdfPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  pagePlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: theme.colors.surfaceMuted,
  },
  pdfStatusOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: theme.colors.overlay,
  },
  placeholderText: {
    color: theme.colors.text,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  nativeHint: {
    color: theme.colors.textSoft,
    fontSize: 12,
    textAlign: 'center',
    maxWidth: 220,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 24,
    padding: 8,
    backgroundColor: theme.colors.surface,
    borderRadius: 22,
    gap: 8,
    ...(Platform.OS === 'web'
      ? { boxShadow: `6px 6px 12px ${theme.neu.colors.darkShadow}, -6px -6px 12px ${theme.neu.colors.lightShadow}` } as any
      : {
          shadowColor: '#000',
          shadowOffset: { width: 5, height: 5 },
          shadowOpacity: 0.45,
          shadowRadius: 10,
          elevation: 8,
        }),
  },
  toolBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeToolBtn: {
    backgroundColor: theme.colors.accentStrong,
  },
  toolDivider: {
    flex: 1,
  },
  exportBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceSoft,
  },
  bottomPanel: {
    zIndex: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    padding: 18,
    ...(Platform.OS === 'web'
      ? { boxShadow: `8px 8px 16px ${theme.neu.colors.darkShadow}, -8px -8px 16px ${theme.neu.colors.lightShadow}` } as any
      : {
          shadowColor: '#000',
          shadowOffset: { width: 6, height: 6 },
          shadowOpacity: 0.5,
          shadowRadius: 12,
          elevation: 10,
        }),
  },
  modalTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  modalInput: {
    minHeight: 110,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceMuted,
    color: theme.colors.text,
    padding: 12,
    textAlignVertical: 'top',
    ...(Platform.OS === 'web'
      ? { boxShadow: theme.neu.shadowStyles.lightLayerInset.boxShadow } as any
      : {}),
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 14,
  },
  commentAuthor: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  commentBody: {
    color: theme.colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  modalBtnGhost: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceSoft,
  },
  modalBtnGhostText: {
    color: theme.colors.text,
    fontWeight: '600',
  },
  modalBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: theme.colors.accentStrong,
  },
  modalBtnText: {
    color: theme.colors.white,
    fontWeight: '700',
  },
});
